import { Figure } from "types";

export const FIGURE_PATHS: Record<Figure, string> = {
  pencil: "src/assets/images/figures/pencil.svg",
  questionBook: "src/assets/images/figures/questionBook.svg",
  openBook: "src/assets/images/figures/openBook.svg",
  briefcase: "src/assets/images/figures/briefcase.svg",
  bonnet: "src/assets/images/figures/bonnet.svg",
  roundMessage: "src/assets/images/figures/roundMessage.svg",
  rectangleMessage: "src/assets/images/figures/rectangleMessage.svg",
  letter: "src/assets/images/figures/letter.svg",
  phone: "src/assets/images/figures/phone.svg",
  smartphone: "src/assets/images/figures/smartphone.svg",
  goldenCell: "src/assets/images/figures/goldenCell.svg",
  star: "src/assets/images/figures/star.svg",
  diamond: "src/assets/images/figures/diamond.svg",
  teamCell: "src/assets/images/figures/happyTeam.svg",
  teamImage0: "src/assets/images/figures/teamHappy0.svg",
  teamImage1: "src/assets/images/figures/teamHappy1.svg",
  teamImage2: "src/assets/images/figures/teamHappy2.svg",
  teamImage3: "src/assets/images/figures/teamHappy3.svg",
  team: "src/assets/images/figures/happyTeam.svg",
  question: "src/assets/images/figures/question.svg",
  heart: "src/assets/images/figures/heart.svg",
  handshake: "src/assets/images/figures/handshake.svg",
  kpi: "src/assets/images/figures/kpi.svg",
  bulb: "src/assets/images/figures/bulb.svg",
};
